##############################################
# Prowire Management Interface Configuration #
##############################################

# URL at which the prowire API server is reachable
API_URL=

# URL at which the prowire management interface is reachable
MANAGEMENT_URL=