version: '3'

services:
  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-change_me}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-prowire}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/${MONGO_DATABASE:-prowire} --quiet
      interval: 5s
      timeout: 10s
      retries: 10

  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "${API_PUBLIC_PORT:-54844}:${API_PORT:-54844}"
    volumes:
      - ${CERTIFICATES_DIR_PATH:-./certs}:/certs
    environment:
      - API_URL=${API_URL:-http://localhost:54844}
      - ADMIN_PANEL_URL=${ADMIN_PANEL_URL:-http://localhost:8080}
      - API_PORT=${API_PORT:-54844}
      - API_UNSECURE_PORT=54845
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      # - SERVER_CERTIFICATE=${SERVER_CERTIFICATE:-/certs/server.crt}
      # - SERVER_PRIVATE_KEY=${SERVER_PRIVATE_KEY:-/certs/server.key}
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING:-mongodb://root:change_me@mongo:27017/}
      - MONGO_USER
      - MONGO_PASSWORD
      - MONGO_DATABASE
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - SERVER_ID=${SERVER_ID:-unique}
      - ACCESS_TOKEN_EXPIRATION
      - ACCESS_TOKEN_SECRET
      - REFRESH_TOKEN_KEY_BASE64
      - VPN_SERVER_SECRET
      - CA_CERTIFICATE=${CA_CERTIFICATE:-/certs/ca.crt}
      - CA_PRIVATE_KEY=${CA_PRIVATE_KEY:-/certs/ca.key}

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    depends_on:
      api:
        condition: service_started
    ports:
      - "${VPN_SERVER_PUBLIC_PORT:-1195}:${VPN_SERVER_PORT:-1195}/udp"
    volumes:
      - ${CERTIFICATES_DIR_PATH:-./certs}:/certs
    environment:
      - API_URL=http://api:54844
      - VPN_SERVER_SECRET
      - VPN_SERVER_ID=${VPN_SERVER_ID:-unique}
      - VPN_SERVER_DH_PARAM=${VPN_SERVER_DH_PARAM:-/certs/dh2048.pem}
      - VPN_SERVER_PUBLIC_URL=${VPN_SERVER_PUBLIC_URL:-http://localhost:1195}
      - VPN_SERVER_PORT=${VPN_SERVER_PORT:-1195}
      - NODE_TLS_REJECT_UNAUTHORIZED
    cap_add:
      - NET_ADMIN
  
  management:
    build:
      context: ./
      dockerfile: ./management/Dockerfile
    depends_on:
      api:
        condition: service_started
    ports:
      - "${MANAGEMENT_PUBLIC_PORT:-8080}:80"
    environment:
      - API_URL=${API_URL:-http://localhost:54844}
