name: Continuous integration
on:
  # Run on every pull request targeting main
  pull_request:
    branches:  
      - main
  # Run on every push to main
  push:
    branches:  
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci --workspaces
      - name: Build
        run: npm run build --workspaces
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci --workspaces
      - name: Build test tools
        run: npm run build -w pki
      - run: npm run test --if-present --workspaces
